
#ifndef ENVOY_EXTENSIONS_FILTERS_COMMON_FAULT_V3_FAULT_PROTO_UPB_H__UPB_MINITABLE_H_
#define ENVOY_EXTENSIONS_FILTERS_COMMON_FAULT_V3_FAULT_PROTO_UPB_H__UPB_MINITABLE_H_

#include "upb/generated_code_support.h"

#include "upb/port/def.inc"

#ifdef __cplusplus
extern "C" {
#endif

extern const upb_MiniTable envoy__extensions__filters__common__fault__v3__FaultDelay_msg_init;
extern const upb_MiniTable* envoy__extensions__filters__common__fault__v3__FaultDelay_msg_init_ptr;
extern const upb_MiniTable envoy__extensions__filters__common__fault__v3__FaultDelay__HeaderDelay_msg_init;
extern const upb_MiniTable* envoy__extensions__filters__common__fault__v3__FaultDelay__HeaderDelay_msg_init_ptr;
extern const upb_MiniTable envoy__extensions__filters__common__fault__v3__FaultRateLimit_msg_init;
extern const upb_MiniTable* envoy__extensions__filters__common__fault__v3__FaultRateLimit_msg_init_ptr;
extern const upb_MiniTable envoy__extensions__filters__common__fault__v3__FaultRateLimit__FixedLimit_msg_init;
extern const upb_MiniTable* envoy__extensions__filters__common__fault__v3__FaultRateLimit__FixedLimit_msg_init_ptr;
extern const upb_MiniTable envoy__extensions__filters__common__fault__v3__FaultRateLimit__HeaderLimit_msg_init;
extern const upb_MiniTable* envoy__extensions__filters__common__fault__v3__FaultRateLimit__HeaderLimit_msg_init_ptr;

extern const upb_MiniTableFile envoy_extensions_filters_common_fault_v3_fault_proto_upb_file_layout;

#ifdef __cplusplus
}
#endif

#include "upb/port/undef.inc"

#endif
