<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/messages.proto

namespace Grpc\Testing\LoadBalancerAccumulatedStatsResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class MethodStats extends \Google\Protobuf\Internal\Message
{

    protected $rpcs_started = 0;

    private $result;

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\Messages::initOnce();
        parent::__construct($data);
    }

    public function getRpcsStarted()
    {
        return $this->rpcs_started;
    }

    public function setRpcsStarted($var)
    {
        GPBUtil::checkInt32($var);
        $this->rpcs_started = $var;

        return $this;
    }

    public function getResult()
    {
        return $this->result;
    }

    public function setResult($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::INT32);
        $this->result = $arr;

        return $this;
    }

}

class_alias(MethodStats::class, \Grpc\Testing\LoadBalancerAccumulatedStatsResponse_MethodStats::class);
