<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route_guide.proto

namespace Routeguide;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Rectangle extends \Google\Protobuf\Internal\Message
{

    protected $lo = null;

    protected $hi = null;

    public function __construct($data = NULL) {
        \GPBMetadata\RouteGuide::initOnce();
        parent::__construct($data);
    }

    public function getLo()
    {
        return isset($this->lo) ? $this->lo : null;
    }

    public function hasLo()
    {
        return isset($this->lo);
    }

    public function clearLo()
    {
        unset($this->lo);
    }

    public function setLo($var)
    {
        GPBUtil::checkMessage($var, \Routeguide\Point::class);
        $this->lo = $var;

        return $this;
    }

    public function getHi()
    {
        return isset($this->hi) ? $this->hi : null;
    }

    public function hasHi()
    {
        return isset($this->hi);
    }

    public function clearHi()
    {
        unset($this->hi);
    }

    public function setHi($var)
    {
        GPBUtil::checkMessage($var, \Routeguide\Point::class);
        $this->hi = $var;

        return $this;
    }

}
