<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route_guide.proto

namespace Routeguide;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class RouteSummary extends \Google\Protobuf\Internal\Message
{

    protected $point_count = 0;

    protected $feature_count = 0;

    protected $distance = 0;

    protected $elapsed_time = 0;

    public function __construct($data = NULL) {
        \GPBMetadata\RouteGuide::initOnce();
        parent::__construct($data);
    }

    public function getPointCount()
    {
        return $this->point_count;
    }

    public function setPointCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->point_count = $var;

        return $this;
    }

    public function getFeatureCount()
    {
        return $this->feature_count;
    }

    public function setFeatureCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->feature_count = $var;

        return $this;
    }

    public function getDistance()
    {
        return $this->distance;
    }

    public function setDistance($var)
    {
        GPBUtil::checkInt32($var);
        $this->distance = $var;

        return $this;
    }

    public function getElapsedTime()
    {
        return $this->elapsed_time;
    }

    public function setElapsedTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->elapsed_time = $var;

        return $this;
    }

}
