
#ifndef ENVOY_CONFIG_METRICS_V3_STATS_PROTO_UPB_H__UPB_MINITABLE_H_
#define ENVOY_CONFIG_METRICS_V3_STATS_PROTO_UPB_H__UPB_MINITABLE_H_

#include "upb/generated_code_support.h"

#include "upb/port/def.inc"

#ifdef __cplusplus
extern "C" {
#endif

extern const upb_MiniTable envoy__config__metrics__v3__StatsSink_msg_init;
extern const upb_MiniTable* envoy__config__metrics__v3__StatsSink_msg_init_ptr;
extern const upb_MiniTable envoy__config__metrics__v3__StatsConfig_msg_init;
extern const upb_MiniTable* envoy__config__metrics__v3__StatsConfig_msg_init_ptr;
extern const upb_MiniTable envoy__config__metrics__v3__StatsMatcher_msg_init;
extern const upb_MiniTable* envoy__config__metrics__v3__StatsMatcher_msg_init_ptr;
extern const upb_MiniTable envoy__config__metrics__v3__TagSpecifier_msg_init;
extern const upb_MiniTable* envoy__config__metrics__v3__TagSpecifier_msg_init_ptr;
extern const upb_MiniTable envoy__config__metrics__v3__HistogramBucketSettings_msg_init;
extern const upb_MiniTable* envoy__config__metrics__v3__HistogramBucketSettings_msg_init_ptr;
extern const upb_MiniTable envoy__config__metrics__v3__StatsdSink_msg_init;
extern const upb_MiniTable* envoy__config__metrics__v3__StatsdSink_msg_init_ptr;
extern const upb_MiniTable envoy__config__metrics__v3__DogStatsdSink_msg_init;
extern const upb_MiniTable* envoy__config__metrics__v3__DogStatsdSink_msg_init_ptr;
extern const upb_MiniTable envoy__config__metrics__v3__HystrixSink_msg_init;
extern const upb_MiniTable* envoy__config__metrics__v3__HystrixSink_msg_init_ptr;

extern const upb_MiniTableFile envoy_config_metrics_v3_stats_proto_upb_file_layout;

#ifdef __cplusplus
}
#endif

#include "upb/port/undef.inc"

#endif
