<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/control.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class ClientStatus extends \Google\Protobuf\Internal\Message
{

    protected $stats = null;

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\Control::initOnce();
        parent::__construct($data);
    }

    public function getStats()
    {
        return $this->stats;
    }

    public function setStats($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Testing\ClientStats::class);
        $this->stats = $var;

        return $this;
    }

}
