<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/echo_messages.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class EchoRequest extends \Google\Protobuf\Internal\Message
{

    protected $message = '';

    protected $param = null;

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\EchoMessages::initOnce();
        parent::__construct($data);
    }

    public function getMessage()
    {
        return $this->message;
    }

    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    public function getParam()
    {
        return $this->param;
    }

    public function setParam($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Testing\RequestParams::class);
        $this->param = $var;

        return $this;
    }

}
