<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/echo_messages.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class ErrorStatus extends \Google\Protobuf\Internal\Message
{

    protected $code = 0;

    protected $error_message = '';

    protected $binary_error_details = '';

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\EchoMessages::initOnce();
        parent::__construct($data);
    }

    public function getCode()
    {
        return $this->code;
    }

    public function setCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->code = $var;

        return $this;
    }

    public function getErrorMessage()
    {
        return $this->error_message;
    }

    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_message = $var;

        return $this;
    }

    public function getBinaryErrorDetails()
    {
        return $this->binary_error_details;
    }

    public function setBinaryErrorDetails($var)
    {
        GPBUtil::checkString($var, True);
        $this->binary_error_details = $var;

        return $this;
    }

}
