<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/stats.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class HistogramParams extends \Google\Protobuf\Internal\Message
{

    protected $resolution = 0.0;

    protected $max_possible = 0.0;

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\Stats::initOnce();
        parent::__construct($data);
    }

    public function getResolution()
    {
        return $this->resolution;
    }

    public function setResolution($var)
    {
        GPBUtil::checkDouble($var);
        $this->resolution = $var;

        return $this;
    }

    public function getMaxPossible()
    {
        return $this->max_possible;
    }

    public function setMaxPossible($var)
    {
        GPBUtil::checkDouble($var);
        $this->max_possible = $var;

        return $this;
    }

}
