<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/messages.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class LoadBalancerStatsResponse extends \Google\Protobuf\Internal\Message
{

    private $rpcs_by_peer;

    protected $num_failures = 0;

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\Messages::initOnce();
        parent::__construct($data);
    }

    public function getRpcsByPeer()
    {
        return $this->rpcs_by_peer;
    }

    public function setRpcsByPeer($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::INT32);
        $this->rpcs_by_peer = $arr;

        return $this;
    }

    public function getNumFailures()
    {
        return $this->num_failures;
    }

    public function setNumFailures($var)
    {
        GPBUtil::checkInt32($var);
        $this->num_failures = $var;

        return $this;
    }

}
