<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/payloads.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class PayloadConfig extends \Google\Protobuf\Internal\Message
{
    protected $payload;

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\Payloads::initOnce();
        parent::__construct($data);
    }

    public function getBytebufParams()
    {
        return $this->readOneof(1);
    }

    public function setBytebufParams($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Testing\ByteBufferParams::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    public function getSimpleParams()
    {
        return $this->readOneof(2);
    }

    public function setSimpleParams($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Testing\SimpleProtoParams::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    public function getComplexParams()
    {
        return $this->readOneof(3);
    }

    public function setComplexParams($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Testing\ComplexProtoParams::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    public function getPayload()
    {
        return $this->whichOneof("payload");
    }

}
