<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/control.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class PoissonParams extends \Google\Protobuf\Internal\Message
{

    protected $offered_load = 0.0;

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\Control::initOnce();
        parent::__construct($data);
    }

    public function getOfferedLoad()
    {
        return $this->offered_load;
    }

    public function setOfferedLoad($var)
    {
        GPBUtil::checkDouble($var);
        $this->offered_load = $var;

        return $this;
    }

}
