<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/proxy-service.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class ProxyStat extends \Google\Protobuf\Internal\Message
{

    protected $latency = 0.0;

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\ProxyService::initOnce();
        parent::__construct($data);
    }

    public function getLatency()
    {
        return $this->latency;
    }

    public function setLatency($var)
    {
        GPBUtil::checkDouble($var);
        $this->latency = $var;

        return $this;
    }

}
