<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/messages.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class ReconnectParams extends \Google\Protobuf\Internal\Message
{

    protected $max_reconnect_backoff_ms = 0;

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\Messages::initOnce();
        parent::__construct($data);
    }

    public function getMaxReconnectBackoffMs()
    {
        return $this->max_reconnect_backoff_ms;
    }

    public function setMaxReconnectBackoffMs($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_reconnect_backoff_ms = $var;

        return $this;
    }

}
