<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/echo_messages.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class ResponseParams extends \Google\Protobuf\Internal\Message
{

    protected $request_deadline = 0;

    protected $host = '';

    protected $peer = '';

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\EchoMessages::initOnce();
        parent::__construct($data);
    }

    public function getRequestDeadline()
    {
        return $this->request_deadline;
    }

    public function setRequestDeadline($var)
    {
        GPBUtil::checkInt64($var);
        $this->request_deadline = $var;

        return $this;
    }

    public function getHost()
    {
        return $this->host;
    }

    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->host = $var;

        return $this;
    }

    public function getPeer()
    {
        return $this->peer;
    }

    public function setPeer($var)
    {
        GPBUtil::checkString($var, True);
        $this->peer = $var;

        return $this;
    }

}
