<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/control.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class ScenarioResultSummary extends \Google\Protobuf\Internal\Message
{

    protected $qps = 0.0;

    protected $qps_per_server_core = 0.0;

    protected $server_system_time = 0.0;

    protected $server_user_time = 0.0;

    protected $client_system_time = 0.0;

    protected $client_user_time = 0.0;

    protected $latency_50 = 0.0;

    protected $latency_90 = 0.0;

    protected $latency_95 = 0.0;

    protected $latency_99 = 0.0;

    protected $latency_999 = 0.0;

    protected $server_cpu_usage = 0.0;

    protected $successful_requests_per_second = 0.0;

    protected $failed_requests_per_second = 0.0;

    protected $client_polls_per_request = 0.0;

    protected $server_polls_per_request = 0.0;

    protected $server_queries_per_cpu_sec = 0.0;

    protected $client_queries_per_cpu_sec = 0.0;

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\Control::initOnce();
        parent::__construct($data);
    }

    public function getQps()
    {
        return $this->qps;
    }

    public function setQps($var)
    {
        GPBUtil::checkDouble($var);
        $this->qps = $var;

        return $this;
    }

    public function getQpsPerServerCore()
    {
        return $this->qps_per_server_core;
    }

    public function setQpsPerServerCore($var)
    {
        GPBUtil::checkDouble($var);
        $this->qps_per_server_core = $var;

        return $this;
    }

    public function getServerSystemTime()
    {
        return $this->server_system_time;
    }

    public function setServerSystemTime($var)
    {
        GPBUtil::checkDouble($var);
        $this->server_system_time = $var;

        return $this;
    }

    public function getServerUserTime()
    {
        return $this->server_user_time;
    }

    public function setServerUserTime($var)
    {
        GPBUtil::checkDouble($var);
        $this->server_user_time = $var;

        return $this;
    }

    public function getClientSystemTime()
    {
        return $this->client_system_time;
    }

    public function setClientSystemTime($var)
    {
        GPBUtil::checkDouble($var);
        $this->client_system_time = $var;

        return $this;
    }

    public function getClientUserTime()
    {
        return $this->client_user_time;
    }

    public function setClientUserTime($var)
    {
        GPBUtil::checkDouble($var);
        $this->client_user_time = $var;

        return $this;
    }

    public function getLatency50()
    {
        return $this->latency_50;
    }

    public function setLatency50($var)
    {
        GPBUtil::checkDouble($var);
        $this->latency_50 = $var;

        return $this;
    }

    public function getLatency90()
    {
        return $this->latency_90;
    }

    public function setLatency90($var)
    {
        GPBUtil::checkDouble($var);
        $this->latency_90 = $var;

        return $this;
    }

    public function getLatency95()
    {
        return $this->latency_95;
    }

    public function setLatency95($var)
    {
        GPBUtil::checkDouble($var);
        $this->latency_95 = $var;

        return $this;
    }

    public function getLatency99()
    {
        return $this->latency_99;
    }

    public function setLatency99($var)
    {
        GPBUtil::checkDouble($var);
        $this->latency_99 = $var;

        return $this;
    }

    public function getLatency999()
    {
        return $this->latency_999;
    }

    public function setLatency999($var)
    {
        GPBUtil::checkDouble($var);
        $this->latency_999 = $var;

        return $this;
    }

    public function getServerCpuUsage()
    {
        return $this->server_cpu_usage;
    }

    public function setServerCpuUsage($var)
    {
        GPBUtil::checkDouble($var);
        $this->server_cpu_usage = $var;

        return $this;
    }

    public function getSuccessfulRequestsPerSecond()
    {
        return $this->successful_requests_per_second;
    }

    public function setSuccessfulRequestsPerSecond($var)
    {
        GPBUtil::checkDouble($var);
        $this->successful_requests_per_second = $var;

        return $this;
    }

    public function getFailedRequestsPerSecond()
    {
        return $this->failed_requests_per_second;
    }

    public function setFailedRequestsPerSecond($var)
    {
        GPBUtil::checkDouble($var);
        $this->failed_requests_per_second = $var;

        return $this;
    }

    public function getClientPollsPerRequest()
    {
        return $this->client_polls_per_request;
    }

    public function setClientPollsPerRequest($var)
    {
        GPBUtil::checkDouble($var);
        $this->client_polls_per_request = $var;

        return $this;
    }

    public function getServerPollsPerRequest()
    {
        return $this->server_polls_per_request;
    }

    public function setServerPollsPerRequest($var)
    {
        GPBUtil::checkDouble($var);
        $this->server_polls_per_request = $var;

        return $this;
    }

    public function getServerQueriesPerCpuSec()
    {
        return $this->server_queries_per_cpu_sec;
    }

    public function setServerQueriesPerCpuSec($var)
    {
        GPBUtil::checkDouble($var);
        $this->server_queries_per_cpu_sec = $var;

        return $this;
    }

    public function getClientQueriesPerCpuSec()
    {
        return $this->client_queries_per_cpu_sec;
    }

    public function setClientQueriesPerCpuSec($var)
    {
        GPBUtil::checkDouble($var);
        $this->client_queries_per_cpu_sec = $var;

        return $this;
    }

}
