<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/control.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class ScenarioResult extends \Google\Protobuf\Internal\Message
{

    protected $scenario = null;

    protected $latencies = null;

    private $client_stats;

    private $server_stats;

    private $server_cores;

    protected $summary = null;

    private $client_success;

    private $server_success;

    private $request_results;

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\Control::initOnce();
        parent::__construct($data);
    }

    public function getScenario()
    {
        return $this->scenario;
    }

    public function setScenario($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Testing\Scenario::class);
        $this->scenario = $var;

        return $this;
    }

    public function getLatencies()
    {
        return $this->latencies;
    }

    public function setLatencies($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Testing\HistogramData::class);
        $this->latencies = $var;

        return $this;
    }

    public function getClientStats()
    {
        return $this->client_stats;
    }

    public function setClientStats($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Grpc\Testing\ClientStats::class);
        $this->client_stats = $arr;

        return $this;
    }

    public function getServerStats()
    {
        return $this->server_stats;
    }

    public function setServerStats($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Grpc\Testing\ServerStats::class);
        $this->server_stats = $arr;

        return $this;
    }

    public function getServerCores()
    {
        return $this->server_cores;
    }

    public function setServerCores($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->server_cores = $arr;

        return $this;
    }

    public function getSummary()
    {
        return $this->summary;
    }

    public function setSummary($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Testing\ScenarioResultSummary::class);
        $this->summary = $var;

        return $this;
    }

    public function getClientSuccess()
    {
        return $this->client_success;
    }

    public function setClientSuccess($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BOOL);
        $this->client_success = $arr;

        return $this;
    }

    public function getServerSuccess()
    {
        return $this->server_success;
    }

    public function setServerSuccess($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BOOL);
        $this->server_success = $arr;

        return $this;
    }

    public function getRequestResults()
    {
        return $this->request_results;
    }

    public function setRequestResults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Grpc\Testing\RequestResultCount::class);
        $this->request_results = $arr;

        return $this;
    }

}
