<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/control.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class SecurityParams extends \Google\Protobuf\Internal\Message
{

    protected $use_test_ca = false;

    protected $server_host_override = '';

    protected $cred_type = '';

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\Control::initOnce();
        parent::__construct($data);
    }

    public function getUseTestCa()
    {
        return $this->use_test_ca;
    }

    public function setUseTestCa($var)
    {
        GPBUtil::checkBool($var);
        $this->use_test_ca = $var;

        return $this;
    }

    public function getServerHostOverride()
    {
        return $this->server_host_override;
    }

    public function setServerHostOverride($var)
    {
        GPBUtil::checkString($var, True);
        $this->server_host_override = $var;

        return $this;
    }

    public function getCredType()
    {
        return $this->cred_type;
    }

    public function setCredType($var)
    {
        GPBUtil::checkString($var, True);
        $this->cred_type = $var;

        return $this;
    }

}
