<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/stats.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class ServerStats extends \Google\Protobuf\Internal\Message
{

    protected $time_elapsed = 0.0;

    protected $time_user = 0.0;

    protected $time_system = 0.0;

    protected $total_cpu_time = 0;

    protected $idle_cpu_time = 0;

    protected $cq_poll_count = 0;

    protected $core_stats = null;

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\Stats::initOnce();
        parent::__construct($data);
    }

    public function getTimeElapsed()
    {
        return $this->time_elapsed;
    }

    public function setTimeElapsed($var)
    {
        GPBUtil::checkDouble($var);
        $this->time_elapsed = $var;

        return $this;
    }

    public function getTimeUser()
    {
        return $this->time_user;
    }

    public function setTimeUser($var)
    {
        GPBUtil::checkDouble($var);
        $this->time_user = $var;

        return $this;
    }

    public function getTimeSystem()
    {
        return $this->time_system;
    }

    public function setTimeSystem($var)
    {
        GPBUtil::checkDouble($var);
        $this->time_system = $var;

        return $this;
    }

    public function getTotalCpuTime()
    {
        return $this->total_cpu_time;
    }

    public function setTotalCpuTime($var)
    {
        GPBUtil::checkUint64($var);
        $this->total_cpu_time = $var;

        return $this;
    }

    public function getIdleCpuTime()
    {
        return $this->idle_cpu_time;
    }

    public function setIdleCpuTime($var)
    {
        GPBUtil::checkUint64($var);
        $this->idle_cpu_time = $var;

        return $this;
    }

    public function getCqPollCount()
    {
        return $this->cq_poll_count;
    }

    public function setCqPollCount($var)
    {
        GPBUtil::checkUint64($var);
        $this->cq_poll_count = $var;

        return $this;
    }

    public function getCoreStats()
    {
        return $this->core_stats;
    }

    public function setCoreStats($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Core\Stats::class);
        $this->core_stats = $var;

        return $this;
    }

}
