<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/control.proto

namespace Grpc\Testing;

use UnexpectedValueException;

class ServerType
{

    const SYNC_SERVER = 0;

    const ASYNC_SERVER = 1;

    const ASYNC_GENERIC_SERVER = 2;

    const OTHER_SERVER = 3;

    const CALLBACK_SERVER = 4;

    private static $valueToName = [
        self::SYNC_SERVER => 'SYNC_SERVER',
        self::ASYNC_SERVER => 'ASYNC_SERVER',
        self::ASYNC_GENERIC_SERVER => 'ASYNC_GENERIC_SERVER',
        self::OTHER_SERVER => 'OTHER_SERVER',
        self::CALLBACK_SERVER => 'CALLBACK_SERVER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }

    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}
