<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/control.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class ServerStatus extends \Google\Protobuf\Internal\Message
{

    protected $stats = null;

    protected $port = 0;

    protected $cores = 0;

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\Control::initOnce();
        parent::__construct($data);
    }

    public function getStats()
    {
        return $this->stats;
    }

    public function setStats($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Testing\ServerStats::class);
        $this->stats = $var;

        return $this;
    }

    public function getPort()
    {
        return $this->port;
    }

    public function setPort($var)
    {
        GPBUtil::checkInt32($var);
        $this->port = $var;

        return $this;
    }

    public function getCores()
    {
        return $this->cores;
    }

    public function setCores($var)
    {
        GPBUtil::checkInt32($var);
        $this->cores = $var;

        return $this;
    }

}
