<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/payloads.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class SimpleProtoParams extends \Google\Protobuf\Internal\Message
{

    protected $req_size = 0;

    protected $resp_size = 0;

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\Payloads::initOnce();
        parent::__construct($data);
    }

    public function getReqSize()
    {
        return $this->req_size;
    }

    public function setReqSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->req_size = $var;

        return $this;
    }

    public function getRespSize()
    {
        return $this->resp_size;
    }

    public function setRespSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->resp_size = $var;

        return $this;
    }

}
