<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/messages.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class SimpleRequest extends \Google\Protobuf\Internal\Message
{

    protected $response_type = 0;

    protected $response_size = 0;

    protected $payload = null;

    protected $fill_username = false;

    protected $fill_oauth_scope = false;

    protected $response_compressed = null;

    protected $response_status = null;

    protected $expect_compressed = null;

    protected $fill_server_id = false;

    protected $fill_grpclb_route_type = false;

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\Messages::initOnce();
        parent::__construct($data);
    }

    public function getResponseType()
    {
        return $this->response_type;
    }

    public function setResponseType($var)
    {
        GPBUtil::checkEnum($var, \Grpc\Testing\PayloadType::class);
        $this->response_type = $var;

        return $this;
    }

    public function getResponseSize()
    {
        return $this->response_size;
    }

    public function setResponseSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->response_size = $var;

        return $this;
    }

    public function getPayload()
    {
        return $this->payload;
    }

    public function setPayload($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Testing\Payload::class);
        $this->payload = $var;

        return $this;
    }

    public function getFillUsername()
    {
        return $this->fill_username;
    }

    public function setFillUsername($var)
    {
        GPBUtil::checkBool($var);
        $this->fill_username = $var;

        return $this;
    }

    public function getFillOauthScope()
    {
        return $this->fill_oauth_scope;
    }

    public function setFillOauthScope($var)
    {
        GPBUtil::checkBool($var);
        $this->fill_oauth_scope = $var;

        return $this;
    }

    public function getResponseCompressed()
    {
        return $this->response_compressed;
    }

    public function setResponseCompressed($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Testing\BoolValue::class);
        $this->response_compressed = $var;

        return $this;
    }

    public function getResponseStatus()
    {
        return $this->response_status;
    }

    public function setResponseStatus($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Testing\EchoStatus::class);
        $this->response_status = $var;

        return $this;
    }

    public function getExpectCompressed()
    {
        return $this->expect_compressed;
    }

    public function setExpectCompressed($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Testing\BoolValue::class);
        $this->expect_compressed = $var;

        return $this;
    }

    public function getFillServerId()
    {
        return $this->fill_server_id;
    }

    public function setFillServerId($var)
    {
        GPBUtil::checkBool($var);
        $this->fill_server_id = $var;

        return $this;
    }

    public function getFillGrpclbRouteType()
    {
        return $this->fill_grpclb_route_type;
    }

    public function setFillGrpclbRouteType($var)
    {
        GPBUtil::checkBool($var);
        $this->fill_grpclb_route_type = $var;

        return $this;
    }

}
