<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/messages.proto

namespace Grpc\Testing\LoadBalancerStatsResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class MetadataByPeer extends \Google\Protobuf\Internal\Message
{

    private $rpc_metadata;

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\Messages::initOnce();
        parent::__construct($data);
    }

    public function getRpcMetadata()
    {
        return $this->rpc_metadata;
    }

    public function setRpcMetadata($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Grpc\Testing\LoadBalancerStatsResponse\RpcMetadata::class);
        $this->rpc_metadata = $arr;

        return $this;
    }

}

class_alias(MetadataByPeer::class, \Grpc\Testing\LoadBalancerStatsResponse_MetadataByPeer::class);
