<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/messages.proto

namespace Grpc\Testing\LoadBalancerStatsResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class RpcMetadata extends \Google\Protobuf\Internal\Message
{

    private $metadata;

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\Messages::initOnce();
        parent::__construct($data);
    }

    public function getMetadata()
    {
        return $this->metadata;
    }

    public function setMetadata($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Grpc\Testing\LoadBalancerStatsResponse\MetadataEntry::class);
        $this->metadata = $arr;

        return $this;
    }

}

class_alias(RpcMetadata::class, \Grpc\Testing\LoadBalancerStatsResponse_RpcMetadata::class);
