
#ifndef ENVOY_CONFIG_CORE_V3_CONFIG_SOURCE_PROTO_UPB_H__UPB_MINITABLE_H_
#define ENVOY_CONFIG_CORE_V3_CONFIG_SOURCE_PROTO_UPB_H__UPB_MINITABLE_H_

#include "upb/generated_code_support.h"

#include "upb/port/def.inc"

#ifdef __cplusplus
extern "C" {
#endif

extern const upb_MiniTable envoy__config__core__v3__ApiConfigSource_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__ApiConfigSource_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__AggregatedConfigSource_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__AggregatedConfigSource_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__SelfConfigSource_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__SelfConfigSource_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__RateLimitSettings_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__RateLimitSettings_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__PathConfigSource_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__PathConfigSource_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__ConfigSource_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__ConfigSource_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__ExtensionConfigSource_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__ExtensionConfigSource_msg_init_ptr;

extern const upb_MiniTableFile envoy_config_core_v3_config_source_proto_upb_file_layout;

#ifdef __cplusplus
}
#endif

#include "upb/port/undef.inc"

#endif
