
#ifndef ENVOY_CONFIG_CORE_V3_PROTOCOL_PROTO_UPB_H__UPB_MINITABLE_H_
#define ENVOY_CONFIG_CORE_V3_PROTOCOL_PROTO_UPB_H__UPB_MINITABLE_H_

#include "upb/generated_code_support.h"

#include "upb/port/def.inc"

#ifdef __cplusplus
extern "C" {
#endif

extern const upb_MiniTable envoy__config__core__v3__TcpProtocolOptions_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__TcpProtocolOptions_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__QuicKeepAliveSettings_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__QuicKeepAliveSettings_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__QuicProtocolOptions_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__QuicProtocolOptions_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__UpstreamHttpProtocolOptions_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__UpstreamHttpProtocolOptions_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__AlternateProtocolsCacheOptions_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__AlternateProtocolsCacheOptions_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__AlternateProtocolsCacheOptions__AlternateProtocolsCacheEntry_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__AlternateProtocolsCacheOptions__AlternateProtocolsCacheEntry_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__HttpProtocolOptions_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__HttpProtocolOptions_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__Http1ProtocolOptions_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__Http1ProtocolOptions_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__Http1ProtocolOptions__HeaderKeyFormat_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__Http1ProtocolOptions__HeaderKeyFormat_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__Http1ProtocolOptions__HeaderKeyFormat__ProperCaseWords_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__Http1ProtocolOptions__HeaderKeyFormat__ProperCaseWords_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__KeepaliveSettings_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__KeepaliveSettings_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__Http2ProtocolOptions_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__Http2ProtocolOptions_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__Http2ProtocolOptions__SettingsParameter_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__Http2ProtocolOptions__SettingsParameter_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__GrpcProtocolOptions_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__GrpcProtocolOptions_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__Http3ProtocolOptions_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__Http3ProtocolOptions_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__SchemeHeaderTransformation_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__SchemeHeaderTransformation_msg_init_ptr;

extern const upb_MiniTableFile envoy_config_core_v3_protocol_proto_upb_file_layout;

#ifdef __cplusplus
}
#endif

#include "upb/port/undef.inc"

#endif
