
#ifndef ENVOY_CONFIG_CORE_V3_SOCKET_OPTION_PROTO_UPB_H__UPB_MINITABLE_H_
#define ENVOY_CONFIG_CORE_V3_SOCKET_OPTION_PROTO_UPB_H__UPB_MINITABLE_H_

#include "upb/generated_code_support.h"

#include "upb/port/def.inc"

#ifdef __cplusplus
extern "C" {
#endif

extern const upb_MiniTable envoy__config__core__v3__SocketOption_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__SocketOption_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__SocketOption__SocketType_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__SocketOption__SocketType_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__SocketOption__SocketType__Stream_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__SocketOption__SocketType__Stream_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__SocketOption__SocketType__Datagram_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__SocketOption__SocketType__Datagram_msg_init_ptr;
extern const upb_MiniTable envoy__config__core__v3__SocketOptionsOverride_msg_init;
extern const upb_MiniTable* envoy__config__core__v3__SocketOptionsOverride_msg_init_ptr;

extern const upb_MiniTableFile envoy_config_core_v3_socket_option_proto_upb_file_layout;

#ifdef __cplusplus
}
#endif

#include "upb/port/undef.inc"

#endif
