
#ifndef ENVOY_EXTENSIONS_FILTERS_HTTP_FAULT_V3_FAULT_PROTO_UPB_H__UPB_MINITABLE_H_
#define ENVOY_EXTENSIONS_FILTERS_HTTP_FAULT_V3_FAULT_PROTO_UPB_H__UPB_MINITABLE_H_

#include "upb/generated_code_support.h"

#include "upb/port/def.inc"

#ifdef __cplusplus
extern "C" {
#endif

extern const upb_MiniTable envoy__extensions__filters__http__fault__v3__FaultAbort_msg_init;
extern const upb_MiniTable* envoy__extensions__filters__http__fault__v3__FaultAbort_msg_init_ptr;
extern const upb_MiniTable envoy__extensions__filters__http__fault__v3__FaultAbort__HeaderAbort_msg_init;
extern const upb_MiniTable* envoy__extensions__filters__http__fault__v3__FaultAbort__HeaderAbort_msg_init_ptr;
extern const upb_MiniTable envoy__extensions__filters__http__fault__v3__HTTPFault_msg_init;
extern const upb_MiniTable* envoy__extensions__filters__http__fault__v3__HTTPFault_msg_init_ptr;

extern const upb_MiniTableFile envoy_extensions_filters_http_fault_v3_fault_proto_upb_file_layout;

#ifdef __cplusplus
}
#endif

#include "upb/port/undef.inc"

#endif
