<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: math.proto

namespace Math;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class DivArgs extends \Google\Protobuf\Internal\Message
{

    protected $dividend = 0;

    protected $divisor = 0;

    public function __construct($data = NULL) {
        \GPBMetadata\Math::initOnce();
        parent::__construct($data);
    }

    public function getDividend()
    {
        return $this->dividend;
    }

    public function setDividend($var)
    {
        GPBUtil::checkInt64($var);
        $this->dividend = $var;

        return $this;
    }

    public function getDivisor()
    {
        return $this->divisor;
    }

    public function setDivisor($var)
    {
        GPBUtil::checkInt64($var);
        $this->divisor = $var;

        return $this;
    }

}
