<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: math.proto

namespace Math;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class FibReply extends \Google\Protobuf\Internal\Message
{

    protected $count = 0;

    public function __construct($data = NULL) {
        \GPBMetadata\Math::initOnce();
        parent::__construct($data);
    }

    public function getCount()
    {
        return $this->count;
    }

    public function setCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->count = $var;

        return $this;
    }

}
