
#ifndef XDS_TYPE_MATCHER_V3_RANGE_PROTO_UPB_H__UPB_MINITABLE_H_
#define XDS_TYPE_MATCHER_V3_RANGE_PROTO_UPB_H__UPB_MINITABLE_H_

#include "upb/generated_code_support.h"

#include "upb/port/def.inc"

#ifdef __cplusplus
extern "C" {
#endif

extern const upb_MiniTable xds__type__matcher__v3__Int64RangeMatcher_msg_init;
extern const upb_MiniTable* xds__type__matcher__v3__Int64RangeMatcher_msg_init_ptr;
extern const upb_MiniTable xds__type__matcher__v3__Int64RangeMatcher__RangeMatcher_msg_init;
extern const upb_MiniTable* xds__type__matcher__v3__Int64RangeMatcher__RangeMatcher_msg_init_ptr;
extern const upb_MiniTable xds__type__matcher__v3__Int32RangeMatcher_msg_init;
extern const upb_MiniTable* xds__type__matcher__v3__Int32RangeMatcher_msg_init_ptr;
extern const upb_MiniTable xds__type__matcher__v3__Int32RangeMatcher__RangeMatcher_msg_init;
extern const upb_MiniTable* xds__type__matcher__v3__Int32RangeMatcher__RangeMatcher_msg_init_ptr;
extern const upb_MiniTable xds__type__matcher__v3__DoubleRangeMatcher_msg_init;
extern const upb_MiniTable* xds__type__matcher__v3__DoubleRangeMatcher_msg_init_ptr;
extern const upb_MiniTable xds__type__matcher__v3__DoubleRangeMatcher__RangeMatcher_msg_init;
extern const upb_MiniTable* xds__type__matcher__v3__DoubleRangeMatcher__RangeMatcher_msg_init_ptr;

extern const upb_MiniTableFile xds_type_matcher_v3_range_proto_upb_file_layout;

#ifdef __cplusplus
}
#endif

#include "upb/port/undef.inc"

#endif
