// Copyright 2023 gRPC authors.

#ifndef GRPC_SRC_CORE_CALL_CUSTOM_METADATA_H
#define GRPC_SRC_CORE_CALL_CUSTOM_METADATA_H

#define GRPC_CUSTOM_CLIENT_METADATA
#define GRPC_CUSTOM_SERVER_METADATA

#endif
