
#ifndef ENVOY_CONFIG_CLUSTER_V3_CIRCUIT_BREAKER_PROTO_UPB_H__UPB_MINITABLE_H_
#define ENVOY_CONFIG_CLUSTER_V3_CIRCUIT_BREAKER_PROTO_UPB_H__UPB_MINITABLE_H_

#include "upb/generated_code_support.h"

#include "upb/port/def.inc"

#ifdef __cplusplus
extern "C" {
#endif

extern const upb_MiniTable envoy__config__cluster__v3__CircuitBreakers_msg_init;
extern const upb_MiniTable* envoy__config__cluster__v3__CircuitBreakers_msg_init_ptr;
extern const upb_MiniTable envoy__config__cluster__v3__CircuitBreakers__Thresholds_msg_init;
extern const upb_MiniTable* envoy__config__cluster__v3__CircuitBreakers__Thresholds_msg_init_ptr;
extern const upb_MiniTable envoy__config__cluster__v3__CircuitBreakers__Thresholds__RetryBudget_msg_init;
extern const upb_MiniTable* envoy__config__cluster__v3__CircuitBreakers__Thresholds__RetryBudget_msg_init_ptr;

extern const upb_MiniTableFile envoy_config_cluster_v3_circuit_breaker_proto_upb_file_layout;

#ifdef __cplusplus
}
#endif

#include "upb/port/undef.inc"

#endif
