<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/empty.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class EmptyMessage extends \Google\Protobuf\Internal\Message
{

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\PBEmpty::initOnce();
        parent::__construct($data);
    }

}
