<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/messages.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class LoadBalancerStatsRequest extends \Google\Protobuf\Internal\Message
{

    protected $num_rpcs = 0;

    protected $timeout_sec = 0;

    private $metadata_keys;

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\Messages::initOnce();
        parent::__construct($data);
    }

    public function getNumRpcs()
    {
        return $this->num_rpcs;
    }

    public function setNumRpcs($var)
    {
        GPBUtil::checkInt32($var);
        $this->num_rpcs = $var;

        return $this;
    }

    public function getTimeoutSec()
    {
        return $this->timeout_sec;
    }

    public function setTimeoutSec($var)
    {
        GPBUtil::checkInt32($var);
        $this->timeout_sec = $var;

        return $this;
    }

    public function getMetadataKeys()
    {
        return $this->metadata_keys;
    }

    public function setMetadataKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->metadata_keys = $arr;

        return $this;
    }

}
