<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/messages.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class LoadBalancerAccumulatedStatsResponse extends \Google\Protobuf\Internal\Message
{

    private $num_rpcs_started_by_method;

    private $num_rpcs_succeeded_by_method;

    private $num_rpcs_failed_by_method;

    private $stats_per_method;

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\Messages::initOnce();
        parent::__construct($data);
    }

    public function getNumRpcsStartedByMethod()
    {
        @trigger_error('num_rpcs_started_by_method is deprecated.', E_USER_DEPRECATED);
        return $this->num_rpcs_started_by_method;
    }

    public function setNumRpcsStartedByMethod($var)
    {
        @trigger_error('num_rpcs_started_by_method is deprecated.', E_USER_DEPRECATED);
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::INT32);
        $this->num_rpcs_started_by_method = $arr;

        return $this;
    }

    public function getNumRpcsSucceededByMethod()
    {
        @trigger_error('num_rpcs_succeeded_by_method is deprecated.', E_USER_DEPRECATED);
        return $this->num_rpcs_succeeded_by_method;
    }

    public function setNumRpcsSucceededByMethod($var)
    {
        @trigger_error('num_rpcs_succeeded_by_method is deprecated.', E_USER_DEPRECATED);
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::INT32);
        $this->num_rpcs_succeeded_by_method = $arr;

        return $this;
    }

    public function getNumRpcsFailedByMethod()
    {
        @trigger_error('num_rpcs_failed_by_method is deprecated.', E_USER_DEPRECATED);
        return $this->num_rpcs_failed_by_method;
    }

    public function setNumRpcsFailedByMethod($var)
    {
        @trigger_error('num_rpcs_failed_by_method is deprecated.', E_USER_DEPRECATED);
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::INT32);
        $this->num_rpcs_failed_by_method = $arr;

        return $this;
    }

    public function getStatsPerMethod()
    {
        return $this->stats_per_method;
    }

    public function setStatsPerMethod($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Grpc\Testing\LoadBalancerAccumulatedStatsResponse\MethodStats::class);
        $this->stats_per_method = $arr;

        return $this;
    }

}
