<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/messages.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class MemorySize extends \Google\Protobuf\Internal\Message
{

    protected $rss = 0;

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\Messages::initOnce();
        parent::__construct($data);
    }

    public function getRss()
    {
        return $this->rss;
    }

    public function setRss($var)
    {
        GPBUtil::checkInt64($var);
        $this->rss = $var;

        return $this;
    }

}
