<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/messages.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class SetReturnStatusRequest extends \Google\Protobuf\Internal\Message
{

    protected $grpc_code_to_return = 0;

    protected $grpc_status_description = '';

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\Messages::initOnce();
        parent::__construct($data);
    }

    public function getGrpcCodeToReturn()
    {
        return $this->grpc_code_to_return;
    }

    public function setGrpcCodeToReturn($var)
    {
        GPBUtil::checkInt32($var);
        $this->grpc_code_to_return = $var;

        return $this;
    }

    public function getGrpcStatusDescription()
    {
        return $this->grpc_status_description;
    }

    public function setGrpcStatusDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->grpc_status_description = $var;

        return $this;
    }

}
