<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/messages.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class StreamingInputCallResponse extends \Google\Protobuf\Internal\Message
{

    protected $aggregated_payload_size = 0;

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\Messages::initOnce();
        parent::__construct($data);
    }

    public function getAggregatedPayloadSize()
    {
        return $this->aggregated_payload_size;
    }

    public function setAggregatedPayloadSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->aggregated_payload_size = $var;

        return $this;
    }

}
