<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/grpc/testing/messages.proto

namespace Grpc\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class TestOrcaReport extends \Google\Protobuf\Internal\Message
{

    protected $cpu_utilization = 0.0;

    protected $memory_utilization = 0.0;

    private $request_cost;

    private $utilization;

    public function __construct($data = NULL) {
        \GPBMetadata\Src\Proto\Grpc\Testing\Messages::initOnce();
        parent::__construct($data);
    }

    public function getCpuUtilization()
    {
        return $this->cpu_utilization;
    }

    public function setCpuUtilization($var)
    {
        GPBUtil::checkDouble($var);
        $this->cpu_utilization = $var;

        return $this;
    }

    public function getMemoryUtilization()
    {
        return $this->memory_utilization;
    }

    public function setMemoryUtilization($var)
    {
        GPBUtil::checkDouble($var);
        $this->memory_utilization = $var;

        return $this;
    }

    public function getRequestCost()
    {
        return $this->request_cost;
    }

    public function setRequestCost($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->request_cost = $arr;

        return $this;
    }

    public function getUtilization()
    {
        return $this->utilization;
    }

    public function setUtilization($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->utilization = $arr;

        return $this;
    }

}
