
#ifndef ENVOY_CONFIG_ENDPOINT_V3_LOAD_REPORT_PROTO_UPB_H__UPB_MINITABLE_H_
#define ENVOY_CONFIG_ENDPOINT_V3_LOAD_REPORT_PROTO_UPB_H__UPB_MINITABLE_H_

#include "upb/generated_code_support.h"

#include "upb/port/def.inc"

#ifdef __cplusplus
extern "C" {
#endif

extern const upb_MiniTable envoy__config__endpoint__v3__UpstreamLocalityStats_msg_init;
extern const upb_MiniTable* envoy__config__endpoint__v3__UpstreamLocalityStats_msg_init_ptr;
extern const upb_MiniTable envoy__config__endpoint__v3__UpstreamEndpointStats_msg_init;
extern const upb_MiniTable* envoy__config__endpoint__v3__UpstreamEndpointStats_msg_init_ptr;
extern const upb_MiniTable envoy__config__endpoint__v3__EndpointLoadMetricStats_msg_init;
extern const upb_MiniTable* envoy__config__endpoint__v3__EndpointLoadMetricStats_msg_init_ptr;
extern const upb_MiniTable envoy__config__endpoint__v3__UnnamedEndpointLoadMetricStats_msg_init;
extern const upb_MiniTable* envoy__config__endpoint__v3__UnnamedEndpointLoadMetricStats_msg_init_ptr;
extern const upb_MiniTable envoy__config__endpoint__v3__ClusterStats_msg_init;
extern const upb_MiniTable* envoy__config__endpoint__v3__ClusterStats_msg_init_ptr;
extern const upb_MiniTable envoy__config__endpoint__v3__ClusterStats__DroppedRequests_msg_init;
extern const upb_MiniTable* envoy__config__endpoint__v3__ClusterStats__DroppedRequests_msg_init_ptr;

extern const upb_MiniTableFile envoy_config_endpoint_v3_load_report_proto_upb_file_layout;

#ifdef __cplusplus
}
#endif

#include "upb/port/undef.inc"

#endif
