
apiVersion: e2etest.grpc.io/v1
kind: LoadTest
metadata:
  name: prebuilt_all_languages
spec:
  clients:
  - language: cxx
    pool: ${client_pool}
    run:
    - args:
      - -c
      - |
        GRPC_EXPERIMENTS="${grpc_experiment}" \
        timeout --kill-after="${KILL_AFTER}" "${POD_TIMEOUT}" \
            /source/code/bazel-bin/test/cpp/qps/qps_worker \
            --driver_port="${DRIVER_PORT}"
      command:
      - bash
      image: ${prebuilt_image_prefix}/cxx:${prebuilt_image_tag}
      name: main
  driver:
    language: cxx
    pool: ${driver_pool}
    run:
    - image: ${driver_image}
      name: main
  results:
    bigQueryTable: ${big_query_table}
  servers:
  - language: cxx
    pool: ${server_pool}
    run:
    - args:
      - -c
      - |
        GRPC_EXPERIMENTS="${grpc_experiment}" \
        timeout --kill-after="${KILL_AFTER}" "${POD_TIMEOUT}" \
            /source/code/bazel-bin/test/cpp/qps/qps_worker \
            --driver_port="${DRIVER_PORT}" --server_port=10010
      command:
      - bash
      image: ${prebuilt_image_prefix}/cxx:${prebuilt_image_tag}
      name: main
  timeoutSeconds: ${timeout_seconds}
  ttlSeconds: 86400
