
#ifndef ENVOY_TYPE_MATCHER_V3_HTTP_INPUTS_PROTO_UPB_H__UPB_MINITABLE_H_
#define ENVOY_TYPE_MATCHER_V3_HTTP_INPUTS_PROTO_UPB_H__UPB_MINITABLE_H_

#include "upb/generated_code_support.h"

#include "upb/port/def.inc"

#ifdef __cplusplus
extern "C" {
#endif

extern const upb_MiniTable envoy__type__matcher__v3__HttpRequestHeaderMatchInput_msg_init;
extern const upb_MiniTable* envoy__type__matcher__v3__HttpRequestHeaderMatchInput_msg_init_ptr;
extern const upb_MiniTable envoy__type__matcher__v3__HttpRequestTrailerMatchInput_msg_init;
extern const upb_MiniTable* envoy__type__matcher__v3__HttpRequestTrailerMatchInput_msg_init_ptr;
extern const upb_MiniTable envoy__type__matcher__v3__HttpResponseHeaderMatchInput_msg_init;
extern const upb_MiniTable* envoy__type__matcher__v3__HttpResponseHeaderMatchInput_msg_init_ptr;
extern const upb_MiniTable envoy__type__matcher__v3__HttpResponseTrailerMatchInput_msg_init;
extern const upb_MiniTable* envoy__type__matcher__v3__HttpResponseTrailerMatchInput_msg_init_ptr;
extern const upb_MiniTable envoy__type__matcher__v3__HttpRequestQueryParamMatchInput_msg_init;
extern const upb_MiniTable* envoy__type__matcher__v3__HttpRequestQueryParamMatchInput_msg_init_ptr;

extern const upb_MiniTableFile envoy_type_matcher_v3_http_inputs_proto_upb_file_layout;

#ifdef __cplusplus
}
#endif

#include "upb/port/undef.inc"

#endif
